#![feature(rustc_private)]

use clippy_config::{ClippyConfiguration, get_configuration_metadata};
use clippy_lints::declared_lints;
use itertools::Itertools;
use regex::Regex;
use std::borrow::Cow;
use std::collections::{BTreeMap, HashMap};
use std::{env, fs};

fn metadata() -> impl Iterator<Item = ClippyConfiguration> {
    get_configuration_metadata()
        .into_iter()
        .filter(|config| config.deprecation_reason.is_none())
        .filter(|config| !config.lints.is_empty())
}

/// Builds a mapping from lint name (lowercase, without `clippy::` prefix) to its group/category.
fn lint_group_map() -> HashMap<String, &'static str> {
    declared_lints::LINTS
        .iter()
        .map(|info| (info.name_lower(), info.category.name()))
        .collect()
}

#[test]
fn book() {
    let path = "book/src/lint_configuration.md";
    let current = fs::read_to_string(path).unwrap();

    let lint_groups = lint_group_map();

    // Separate configs into two buckets:
    // - multi-lint configs: affect more than one lint (regardless of group)
    // - single-lint configs: affect exactly one lint, grouped by group then lint
    let mut multi_lint_configs: Vec<ClippyConfiguration> = Vec::new();
    // group -> lint_name -> Vec<config>
    let mut single_lint: BTreeMap<&str, BTreeMap<&str, Vec<ClippyConfiguration>>> = BTreeMap::new();

    for conf in metadata() {
        if conf.lints.len() > 1 {
            multi_lint_configs.push(conf);
        } else {
            let lint_name = conf.lints[0];
            let group = lint_groups.get(lint_name).copied().unwrap_or("unknown");
            single_lint
                .entry(group)
                .or_default()
                .entry(lint_name)
                .or_default()
                .push(conf);
        }
    }

    let mut sections = Vec::new();

    // "Multiple Lints" section
    if !multi_lint_configs.is_empty() {
        let mut s = String::from("# Multiple Lints\n\n");
        s.push_str(
            &multi_lint_configs
                .iter()
                .map(|conf| conf.to_markdown_heading3_with_lints(&lint_groups))
                .join("\n"),
        );
        sections.push(s);
    }

    // Per-group sections: # Group > ## Lint > ### Config
    for (group, lints) in &single_lint {
        let mut s = format!("# {}\n\n", capitalize(group));
        let lint_sections: Vec<String> = lints
            .iter()
            .map(|(lint_name, configs)| {
                let mut ls = format!(
                    "## [`{lint_name}`](https://rust-lang.github.io/rust-clippy/master/index.html#{lint_name})\n\n"
                );
                ls.push_str(&configs.iter().map(|conf| conf.to_markdown_heading3()).join("\n"));
                ls
            })
            .collect();
        s.push_str(&lint_sections.join("\n"));
        sections.push(s);
    }

    let expected = format!(
        r"<!--
This file is generated by `cargo bless --test config-metadata`.
Please use that command to update the file and do not edit it by hand.
-->

# Lint Configuration Options

The following list shows each configuration option, along with a description, its default value, an example
and lints affected.

---

{}
",
        sections.join("\n---\n\n").trim(),
    );

    if current != expected {
        if env::var_os("RUSTC_BLESS").is_some_and(|v| v != "0") {
            fs::write(path, expected).unwrap();
        } else {
            panic!("`{path}` is out of date, run `cargo bless --test config-metadata` to update it");
        }
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[test]
fn changelog() {
    let path = "CHANGELOG.md";
    let current = fs::read_to_string(path).unwrap();

    let configs = metadata().map(|conf| conf.to_markdown_link()).join("\n");

    let re = Regex::new(
        "(?s)\
        (<!-- begin autogenerated links to configuration documentation -->)\
        .*\
        (<!-- end autogenerated links to configuration documentation -->)\
        ",
    )
    .unwrap();
    let expected = re.replace(&current, format!("$1\n{configs}\n$2"));

    assert!(
        matches!(expected, Cow::Owned(_)),
        "failed to find configuration section in `{path}`"
    );

    if current != expected {
        if env::var_os("RUSTC_BLESS").is_some_and(|v| v != "0") {
            fs::write(path, expected.as_bytes()).unwrap();
        } else {
            panic!("`{path}` is out of date, run `cargo bless --test config-metadata` to update it");
        }
    }
}
